package com.madikhan.estore.constants;

public class NamesConstants {

    public static final Boolean USER_ROLE = false;
    public static final Boolean ADMIN_ROLE = true;

    public static final String IS_ADMIN = "isAdmin";
    public static final String ID = "id";
    public static final String USER_ID_ATTRIBUTE = "userID";
    public static final String ORDER_ID_ATTRIBUTE = "orderID";
    public static final String PRODUCT_ID_ATTRIBUTE = "productID";
    public static final String ID_PRODUCT_PARAMETER = "idProduct";
    public static final String TOTAL_COUNT_ATTRIBUTE = "totalCount";
    public static final String TOTAL_COST_ATTRIBUTE = "totalCost";
    public static final String NAME = "name";
    public static final String INTERNAL_ERROR = "Internal error";
    public static final String MESSAGE = "message";
    public static final String STATUS_CODE = "statusCode";
    public static final String ORDER = "order";
    public static final String LANGUAGE = "language";
    public static final String DEFAULT_LANGUAGE = "defaultLanguage";
    public static final String DEFAULT_LANGUAGE_ID = "defaultLanguageID";
    public static final String NEW_LANGUAGE = "lang";
    public static final String USER_NAME_ATTRIBUTE = "userName";
    public static final String SURNAME = "surname";
    public static final String USER_SURNAME_ATTRIBUTE = "userSurname";
    public static final String EMAIL = "email";
    public static final String USERS = "users";
    public static final String DESCRIPTION = "description";
    public static final String CATEGORY_ID = "categoryID";
    public static final String PRODUCER_ID = "producerID";
    public static final String PRICE = "price";
    public static final String PRODUCT = "product";
    public static final String USER_EMAIL_ATTRIBUTE = "userEmail";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String CURRENT_MESSAGE = "CURRENT_MESSAGE";
    public static final String ORDER_CREATED_MESSAGE = "Order created successfully. Please wait for our reply.";
    public static final String USER_PHONE_NUMBER_ATTRIBUTE = "userPhoneNumber";
    public static final String ADDRESS = "address";
    public static final String PAGE = "page";
    public static final String QUERY = "query";
    public static final String CATEGORY = "category";
    public static final String PRODUCER = "producer";
    public static final String USER_ADDRESS_ATTRIBUTE = "userAddress";
    public static final String SELECTED_CATEGORY_URL = "selectedCategoryUrl";
    public static final String PASSWORD = "password";
    public static final String NEW_PASSWORD = "newPassword";
    public static final String CONFIRM_NEW_PASSWORD = "confirmNewPassword";
    public static final String LANGUAGE_ID = "languageID";
    public static final String ORDERS = "orders";
    public static final String PAGE_COUNT = "pageCount";
    public static final String PRODUCTS = "products";
    public static final int PROCESSING_STATUS_ID = 1;
    public static final int COMPLETED_STATUS_ID = 2;
    public static final int CANCELED_STATUS_ID = 3;
    public static final int ZERO = 0;


    public static final String MY_ORDERS_TBODY_JSP = "my-orders-tbody.jsp";
    public static final String ADMIN_JSP = "admin.jsp";
    public static final String LOGIN_JSP = "login.jsp";
    public static final String SEARCH_RESULT_JSP = "search-result.jsp";
    public static final String SHOPPING_CART_JSP = "shopping-cart.jsp";
    public static final String UPDATE_PRODUCT_JSP = "update-product.jsp";
    public static final String ORDER_JSP = "order.jsp";
    public static final String REGISTRATION_JSP = "registration.jsp";
    public static final String PROFILE_JSP = "profile.jsp";
    public static final String PRODUCTS_JSP = "products.jsp";
    public static final String MY_ORDERS_LOGIN_JSP = "my-orders.jsp";
    public static final String ERROR_JSP = "error.jsp";
    public static final String CHANGE_PROFILE_JSP = "change-profile.jsp";
    public static final String CREATE_PRODUCT_JSP = "create-product.jsp";
    public static final String ADMIN_PRODUCTS_JSP = "admin-products.jsp";
    public static final String ADMIN_USERS_JSP = "admin-users.jsp";
    public static final String ADMIN_ORDERS_TBODY_JSP = "admin-orders-tbody.jsp";
    public static final String ADMIN_USERS_TBODY_JSP = "admin-users-tbody.jsp";
    public static final String ADMIN_PRODUCTS_TBODY_JSP = "admin-products-tbody.jsp";
    public static final String CURRENT_SHOPPING_CART = "CURRENT_SHOPPING_CART";
    public static final String PRODUCT_LIST_JSP = "product-list.jsp";
    public static final String ADMIN_ORDERS_JSP = "admin-orders.jsp";
    public static final int MAX_PRODUCT_COUNT_PER_SHOPPING_CART = 10;
    public static final int MAX_PRODUCTS_PER_SHOPPING_CART = 20;
    public static final int MAX_USERS_PER_SHOPPING_CART = 20;
    public static final int MAX_PRODUCTS_PER_HTML_PAGE = 24;
    public static final int MAX_ORDERS_PER_HTML_PAGE = 24;
    public static final int MAX_ORDERS_PER_ADMIN_PAGE = 20;
    public static final int MAX_PRODUCTS_PER_ADMIN_PAGE = 50;
    public static final long NUMBER_OF_FIRST_PAGE = 1;

    public static final String  CURRENT_USER = "CURRENT_USER";

    public static final String EMAIL_AUTH_ERROR = "emailAuthError";
    public static final String PASSWORD_AUTH_ERROR = "passwordAuthError";
    public static final String EMAIL_IS_WRONG_MESSAGE = "Email is wrong";
    public static final String REQUEST_NOT_VALID_MESSAGE = "Request is not valid: ";
    public static final String PASSWORD_IS_WRONG_MESSAGE = "password.is.wrong";
    public static final String YOU_ARE_NOT_ADMIN_MESSAGE = "You are not Admin!";
    public static final String PASSWORD_IS_WRONG = "passwordIsWrong";
    public static final String PRODUCT_COUNT = "productCount";
    public static final String SEARCH_FORM = "searchForm";
    public static final String CATEGORY_LIST = "categoryList";
    public static final String PRODUCER_LIST = "producerList";
    public static final String NEW_PASSWORD_IS_WRONG = "newPasswordIsWrong";
    public static final String PRODUCT_UPDATE_ERROR = "ProductUpdateError";
    public static final String PRODUCT_UPDATE_ERROR_CAUSE = "Product already in order!";
    public static final String NEW_PASSWORD_IS_EMPTY_MESSAGE = "new.password.is.empty";
    public static final String USER_DATA_NOT_COMPLETE = "UserDataIsNotComplete";
    public static final String USER_DATA_NOT_COMPLETE_MESSAGE = "Please fill all your data";
    public static final String THERE_IS_NO_SUCH_PRODUCT_MESSAGE = "There is no such product!";
    public static final String CONFIRM_NEW_PASSWORD_IS_WRONG = "confirmNewPasswordIsWrong";
    public static final String ACCOUNT_WITH_ID_NOT_OWNER_ORDER = "Account with id = %s is not owner for order with id = %s";
    public static final String CONFIRM_NEW_PASSWORD_IS_EMPTY_MESSAGE = "confirm.new.password.is.empty";
    public static final String CONFIRM_NEW_PASSWORD_IS_WRONG_MESSAGE = "confirm.new.password.is.wrong";
    public static final String CONFIRM_PASSWORD = "confirmPassword";
    public static final String PASSWORD_DOES_NOT_MATCH_MESSAGE = "Password does not match!";
    public static final String EMAIL_IS_WRONG = "emailIsWrong";
    public static final String EMAIL_EXISTS_MESSAGE = "Login already exists!";
    public static final String EMAIL_WRONG_FORMAT_MESSAGE = "Email format wrong: A-Za-z0-9@a-z.a-z";
    public static final String PASSWORD_WRONG_FORMAT_MESSAGE = "password.format.wrong";
    public static final String PHONE_NUMBER_WRONG_FORMAT = "phoneNumberWrong";
    public static final String ERROR_POOL_SIZE_PROPERTIES = "Cannot get pool size from properties!";
    public static final String ERROR_FIND_JDBC_DRIVER_CLASS = "Cannot find driver class for jdbc!";
    public static final String ERROR_THREAD_INTERRUPTED_WHILE_INIT_CONNECTION = "Thread interrupted while init connection";
    public static final String ERROR_THREAD_INTERRUPTED_WHILE_GET_CONNECTION = "Thread interrupted while get connection";
    public static final String ERROR_THREAD_INTERRUPTED_WHILE_BRING_BACK_CONNECTION = "Thread interrupted while bring back connection";
    public static final String ERROR_CANNOT_OPEN_CONNECTION = "Cannot open connection (url, username, password is not correct)";
    public static final String PHONE_NUMBER_WRONG_FORMAT_MESSAGE = "phone.format.wrong";
    public static final String USER_HAS_ORDERS_MESSAGE = "User has one or more orders!";

    public static final String LOGIN = "login";
    public static final String HOME_PAGE_PATH = "/";
    public static final String ERROR_PAGE_PATH ="/error";
    public static final String MEDIA_FOLDER_PATH = "/media";
    public static final String PRODUCTS_PATH = "/products";
    public static final String LOGIN_PAGE_PATH = "/loginPage";
    public static final String REGISTRATION_PAGE_PATH = "/registrationPage";
    public static final String PRODUCTS_BY_CATEGORY_PATH = "/productsByCategory";
    public static final String ADMIN_PRODUCTS_PAGE_PATH = "/adminProductsPage";
    public static final String JPG_FORMAT = ".jpg";
    public static final String ORDER_PAGE_WITH_PARAMETER_PATH = "/order?id=";
    public static final String UPDATE_PRODUCT_PAGE_WITH_PARAMETER_PATH = "/updateProductPage?id=";
    public static final String PROFILE_PAGE_PATH ="/profile";
    public static final String CHANGE_PROFILE_PAGE = "/changeProfile";
    public static final String LOAD_MORE_PRODUCTS_BY_CATEGORY_PATH = "/more/productsByCategory";

}
